routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::group(['prefix' => 'cust'], function () {
    Auth::routes(['verify' => true]);
});

Route::group(['as' => 'customer.'], function () {
    Route::get('/', 'CustomerController@index');
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('login', 'AuthAdminController@showLoginForm')->name('admin.login');
    Route::post('login', 'AuthAdminController@login')->name('admin.postlogin');
    Route::post('logout', 'AuthAdminController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('/', 'AdminController');
    Route::resource('/agama', 'AgamaController');
    Route::resource('/sambutan', 'SambutanController');
    Route::resource('/pesanan', 'PesananController');
    Route::put('/pesanan/ubahStatus/{id}', 'PesananController@changeStatus')->name('pesanan.changeStatus');
});

// Route::group(['prefix'=>'/admin','middleware'=>'admin'],function(){
//     Route::resource('/','AdminController');
// });

Route::get('/home', 'HomeController@index')->name('home');

app/Pesanan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Pesanan extends Model
{
    use SoftDeletes;

    protected $table = "undangans";
    protected $guarded = [];

    protected $with = ['sambutan','harga'];

    public function sambutan()
    {
        return $this->belongsTo(Sambutan::class, 'sambutan_id');
    }

    public function harga(){
        return $this->belongsTo(Harga::class, ' harga_id');
    }

    public static function getOrderStatus($status){
        if ($status == "0"){
            return "Menunggu Verifikasi";
        }else if ($status == "1"){
            return "Terverifikasi";
        }else if($status == "2"){
            return "Link Terkirim";
        }else if($status == "3"){
            return "Selesai";
        }
        else{
            return "Tidak Terverifikasi";
        }
    }
}

app/Http/Controllers/PesananController.php
<?php

namespace App\Http\Controllers;

use App\Pesanan;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class PesananController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Pesanan::get();
        return view("admin.pesanan.index", compact("data"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Pesanan $pesanan
     * @return \Illuminate\Http\Response
     */
    public function show(Pesanan $pesanan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Pesanan $pesanan
     * @return \Illuminate\Http\Response
     */
    public function edit(Pesanan $pesanan)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Pesanan $pesanan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Pesanan $pesanan)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Pesanan $pesanan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pesanan $pesanan)
    {
        //
    }

    public function changeStatus(Request $request, $id)
    {
        $pesanan = Pesanan::find($id);
        $pesanan->status = $request->status;
        $pesanan->save();
        return redirect()->back()->with('success', $this->SUCCESS_UPDATE_MESSAGE);
    }


}

resources/views/admin/pesanan/index.blade.php
@extends('layouts.layout')
@section('title','Pesanan')
@section('content')
    <div class="row pt-2">
        <div class="col-md-12">
            <div class="card card-green">
                <div class="card-header">
                    <h3 class="card-title">Pesanan</h3>
                </div>

                <div class="card-body ">
                    <div class="table-responsive">
                        <table id="table" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Link</th>
                                <th>Mempelai Pria</th>
                                <th>Mempelai Wanita</th>
                                <th>Status</th>
                                <th>Tanggal Dibuat</th>
                                <th>Bukti Pembayaran</th>
                                <th>Ubah Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($data as $m)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>widianapw.com/{{ $m->subdomain }}</td>
                                    <td>{{ $m->guy_nickname }}</td>
                                    <td>{{ $m->girl_nickname }}</td>
                                    <td>
                                        {{\App\Pesanan::getOrderStatus($m->status)}}
                                    </td>
                                    <td>@dateFormat($m->created_at)</td>
                                    <td>
                                        <center>
                                            <button data-toggle="modal" data-target="#exampleModal"
                                                    id="btnSeePaymentProof" class="btn btn-primary">
                                                <i class="fa fa-eye"></i>
                                            </button>
                                        </center>
                                    </td>
                                    <td>
                                        <center>
                                            <div class="btn-group">
                                                <div class="btn-group">
                                                    <button type="button" class="btn btn-success dropdown-toggle"
                                                            data-toggle="dropdown">
                                                        Aksi
                                                    </button>
                                                    <div class="dropdown-menu">
                                                        <a class="dropdown-item"
                                                           href="{{route("admin.pesanan.changeStatus",["id"=>$m->id])}}"
                                                           onclick="event.preventDefault(); document.getElementById('status').value='1'; document.getElementById('changeStatusForm').submit() ">Verifikasi</a>
                                                        <a class="dropdown-item"
                                                           href="{{route("admin.pesanan.changeStatus",["id"=>$m->id])}}"
                                                           onclick="event.preventDefault(); document.getElementById('status').value='2'; document.getElementById('changeStatusForm').submit() ">Link
                                                            Terkirim</a>
                                                        <a class="dropdown-item"
                                                           href="{{route("admin.pesanan.changeStatus",["id"=>$m->id])}}"
                                                           onclick="event.preventDefault(); document.getElementById('status').value='3'; document.getElementById('changeStatusForm').submit() ">
                                                            Selesai
                                                        </a>
                                                        <a class="dropdown-item"
                                                           href="{{route("admin.pesanan.changeStatus",["id"=>$m->id])}}"
                                                           onclick="event.preventDefault(); document.getElementById('status').value='4'; document.getElementById('changeStatusForm').submit() ">Tidak
                                                            Terverifikasi</a>

                                                        <form
                                                            id="changeStatusForm"
                                                            action="{{route("admin.pesanan.changeStatus",["id"=>$m->id])}}"
                                                            method="POST" style="display: none">
                                                            @csrf
                                                            @method("PUT")
                                                            <input type="hidden" id="status" name="status" value="1">
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </center>
                                    </td>

                                </tr>
                                <div class="modal fade" id="exampleModal" tabindex="-1"
                                     aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Bukti Pembayaran</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <img class="img-fluid rounded mx-auto d-block "
                                                     src="{{asset('img/payment/'.$m->payment_proof)}}">
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-primary" data-dismiss="modal">
                                                    Tutup
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
@endsection