routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::group(['prefix' => 'cust'], function () {
    Auth::routes(['verify' => true]);
});

Route::group(['as' => 'customer.'], function () {
    Route::get('/', 'CustomerController@index');
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('login', 'AuthAdminController@showLoginForm')->name('admin.login');
    Route::post('login', 'AuthAdminController@login')->name('admin.postlogin');
    Route::post('logout', 'AuthAdminController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('/', 'AdminController');
    Route::resource('/agama', 'AgamaController');
    Route::resource('/sambutan', 'SambutanController');
    Route::resource('/pesanan', 'PesananController');
    Route::put('/pesanan/ubahStatus/{id}', 'PesananController@changeStatus')->name('pesanan.changeStatus');
});

// Route::group(['prefix'=>'/admin','middleware'=>'admin'],function(){
//     Route::resource('/','AdminController');
// });

Route::get('/home', 'HomeController@index')->name('home');

app/Agama.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Agama extends Model
{
    use SoftDeletes;
    protected $table = "agamas";
    protected $guarded = [];

    public function sambutan(){
        return $this->hasMany(Sambutan::class, 'agama_id','id');
    }
}

app/Http/Controllers/AgamaController.php
<?php

namespace App\Http\Controllers;

use App\Agama;
use Illuminate\Http\Request;

class AgamaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Agama::with('sambutan')->get();
        return view("admin.agama.index", compact("data"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.agama.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Agama::insert($request->except(['_token']));
        return redirect()->route('admin.agama.index')->with('success', $this->SUCCESS_ADD_MESSAGE);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Agama $agama
     * @return \Illuminate\Http\Response
     */
    public function show(Agama $agama)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Agama $agama
     * @return \Illuminate\Http\Response
     */
    public function edit(Agama $agama)
    {
        return view("admin.agama.edit", compact("agama"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Agama $agama
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agama $agama)
    {
        Agama::find($agama->id)->update($request->all());
        return redirect()->route('admin.agama.index')->with('success', $this->SUCCESS_UPDATE_MESSAGE);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Agama $agama
     * @return \Illuminate\Http\Response
     */
    public function destroy(Agama $agama)
    {
        Agama::find($agama->id)->delete();
        return redirect()->route('admin.agama.index')->with('success', $this->SUCCESS_DELETE_MESSAGE);
    }
}

resources/views/admin/agama/create.blade.php
@extends('layouts.layout')

@section('title','Tambah Agama')
@section('content')
<div class="row pt-2">
    <div class="col-md-12">
        <div class="card card-green">
            <div class="card-header">
                <h3 class="card-title">Agama</h3>
            </div>
            <div class="card-body">
                <form action="{{route('admin.agama.store')}}" method="POST" class="form-group">
                    @csrf
                    <div class="form-body">
                        <div class="form-label">
                            <label for="agama">Agama</label>
                        </div>
                        <input type="text" id="agana" name="agama" class="form-control">
                
                        <br>
                        <div class="form-footer">
                            <button type="submit" class="btn btn-primary">Tambah</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/admin/agama/edit.blade.php
@extends('layouts.layout')

@section('title','Edit Agama')
@section('content')
    <div class="row pt-2">
        <div class="col-md-12">
            <div class="card card-green">
                <div class="card-header">
                    <h3 class="card-title">Agama</h3>
                </div>
                <div class="card-body">
                    <form action="{{route('admin.agama.update',['agama'=>$agama->id])}}" method="POST" class="form-group">
                        @csrf
                        @method("PUT")
                        <div class="form-body">
                            <div class="form-label">
                                <label for="agama">Agama</label>
                            </div>
                            <input type="text" id="agana" name="agama" class="form-control" value="{{$agama->agama}}">

                            <br>
                            <div class="form-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/agama/index.blade.php
@extends('layouts.layout')
@section('title','Agama')
@section('content')
    <div class="row pt-2">
        <div class="col-md-12">
            <div class="card card-green">
                <div class="card-header">
                    <h3 class="card-title">Agama</h3>
                </div>

                <div class="card-body ">
                    <a href="{{route('admin.agama.create')}}">
                        <button class="btn btn-primary mb-4"><i class="fa fa-plus"></i>
                            Tambah Data
                        </button>
                    </a>
                    <div class="table-responsive">
                        <table id="table" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Agama</th>
                                <th>Tanggal Dibuat</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($data as $m)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $m->agama }}</td>
                                    <td>@dateFormat($m->created_at)</td>
                                    <td>

                                        <a href="{{route('admin.agama.edit',['agama'=>$m->id])}}">
                                            <button type="submit" class="btn btn-warning">
                                                <i class="fa fa-fw fa-edit" style="color:white"></i>
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <form action="{{route('admin.agama.destroy',['agama'=>$m->id])}}" method="POST">
                                            @method("DELETE")
                                            @csrf
                                            <button type="submit" onclick="return confirm('Are you sure?')"
                                                    class="btn btn-danger">
                                                <i class="fa fa-fw fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
@endsection