routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::group(['prefix' => 'cust'], function () {
    Auth::routes(['verify' => true]);
});

Route::group(['as' => 'customer.'], function () {
    Route::get('/', 'CustomerController@index');
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('login', 'AuthAdminController@showLoginForm')->name('admin.login');
    Route::post('login', 'AuthAdminController@login')->name('admin.postlogin');
    Route::post('logout', 'AuthAdminController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('/', 'AdminController');
    Route::resource('/agama', 'AgamaController');
    Route::resource('/sambutan', 'SambutanController');
    Route::resource('/pesanan', 'PesananController');
    Route::put('/pesanan/ubahStatus/{id}', 'PesananController@changeStatus')->name('pesanan.changeStatus');
});

// Route::group(['prefix'=>'/admin','middleware'=>'admin'],function(){
//     Route::resource('/','AdminController');
// });

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/customer.blade.php
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Wedding HTML-5 Template </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">

    <!-- CSS here -->
    <link rel="stylesheet" href="{{asset('customers/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/flaticon.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/slicknav.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/animate.min.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/magnific-popup.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/fontawesome-all.min.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/themify-icons.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/slick.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/nice-select.css')}}">
    <link rel="stylesheet" href="{{asset('customers/css/style.css')}}">
</head>

<body>

<!-- Preloader Start -->
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <img src="{{asset('customers/img/logo/logo.png')}}" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Preloader Start -->

<header>
    <!-- Header Start -->
    <div class="header-area">
        <div class="main-header header-sticky">
            <div class="container">
                <div class="row align-items-center">
                    <!-- Logo -->
                    <div class="col-xl-2 col-lg-2 col-md-2">
                        <div class="logo">
                            <a href="/"><img src="{{asset('customers/img/logo/logo.png')}}" alt=""></a>
                        </div>
                    </div>
                    <div class="col-xl-10 col-lg-10 col-md-10">
                        <!-- Main-menu -->
                        <div class="main-menu f-right d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a href="/">Beranda</a></li>
                                    <li><a href="/">Fitur</a></li>
                                    <li><a href="/">Demo</a></li>
                                    <li><a href="/">Masuk / Login</a></li>
{{--                                    <li><a href="#">Pages</a>--}}
{{--                                        <ul class="submenu">--}}
{{--                                            <li><a href="blog.html">Blog</a></li>--}}
{{--                                            <li><a href="single-blog.html">Blog Details</a></li>--}}
{{--                                            <li><a href="elements.html">Element</a></li>--}}
{{--                                        </ul>--}}
{{--                                    </li>--}}
                                    <li><a href="contact.html">Daftar</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>

<main>
    @yield('content')
</main>
<footer>
    <!-- Footer Start-->
    <div class="footer-main footer-bg">
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row d-flex justify-content-between">
                    <div class="col-xl-4 col-lg-4 col-md-5 col-sm-8">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <!-- logo -->
                                <div class="footer-logo">
                                    <a href="index.html"><img src="{{asset('customers/img/logo/logo2_footer.png')}}"
                                                              alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p class="info1">Seddo eiusmod tempor incididunt ut labore et dolore magna
                                            aliqua.</p>

                                        <p class="info2">theaisle@elated-themes.com</p>
                                        <p class="info2">+(123) 456 - 7890 - 456 - 7890</p>
                                        <p class="info2"> 35 W 46nd Street New York</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-md-5 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>WEDDING PLANNER FAQS</h4>
                                <ul>
                                    <li><a href="#">Why Hire a Planner?</a></li>
                                    <li><a href="#">How Can I Make An</a></li>
                                    <li><a href="#">Appointment?</a></li>
                                    <li><a href="#">How to Choose a Venue</a></li>
                                    <li><a href="#">Event Catalogue</a></li>
                                    <li><a href="#"> Accept</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-5 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>ABOUT US</h4>
                                <ul>
                                    <li><a href="#">Bridesmaids</a></li>
                                    <li><a href="#">November 22, 2020</a></li>
                                    <li><a href="#">Groomsmen</a></li>
                                    <li><a href="#">November 22, 2020</a></li>
                                    <li><a href="#">JEWELRY</a></li>
                                    <li><a href="#">November 22, 2020</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-3 col-md-5 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Instagram</h4>
                            </div>
                            <div class="instagram-gellay">
                                <ul class="insta-feed">
                                    <li><a href="#"><img src="{{asset('customers/img/post/instra1.jpg')}}" alt=""></a>
                                    </li>
                                    <li><a href="#"><img src="{{asset('customers/img/post/instra2.jpg')}}" alt=""></a>
                                    </li>
                                    <li><a href="#"><img src="{{asset('customers/img/post/instra3.jpg')}}" alt=""></a>
                                    </li>
                                    <li><a href="#"><img src="{{asset('customers/img/post/instra4.jpg')}}" alt=""></a>
                                    </li>
                                    <li><a href="#"><img src="{{asset('customers/img/post/instra5.jpg')}}" alt=""></a>
                                    </li>
                                    <li><a href="#"><img src="{{asset('customers/img/post/instra6.jpg')}}" alt=""></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer-bottom aera -->
        <div class="footer-bottom-area footer-bg">
            <div class="container">
                <div class="footer-border">
                    <div class="row d-flex align-items-center">
                        <div class="col-xl-12 ">
                            <div class="footer-copy-right text-center">
                                <p>
                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                                    All rights reserved | This template is made with <i class="ti-heart"
                                                                                        aria-hidden="true"></i> by <a
                                        href="https://colorlib.com" target="_blank">Colorlib</a>
                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End-->
</footer>

<!-- JS here -->

<!-- All JS Custom Plugins Link Here here -->
<script src="{{asset('customers/js/vendor/modernizr-3.5.0.min.js')}}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{{asset('customers/js/vendor/jquery-1.12.4.min.js')}}"></script>
<script src="{{asset('customers/js/popper.min.js')}}"></script>
<script src="{{asset('customers/js/bootstrap.min.js')}}"></script>

<!-- Jquery Mobile Menu -->
<script src="{{asset('customers/js/jquery.slicknav.min.js')}}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{{asset('customers/js/owl.carousel.min.js')}}"></script>
<script src="{{asset('customers/js/slick.min.js')}}"></script>

<!-- Date Picker -->
<script src="{{asset('customers/js/gijgo.min.js')}}"></script>

<!-- One Page, Animated-HeadLin -->
<script src="{{asset('customers/js/wow.min.js')}}"></script>
<script src="{{asset('customers/js/animated.headline.js')}}"></script>
<script src="{{asset('customers/js/jquery.magnific-popup.js')}}"></script>

<!-- Scrollup, nice-select, sticky -->
<script src="{{asset('customers/js/jquery.scrollUp.min.js')}}"></script>
<script src="{{asset('customers/js/jquery.nice-select.min.js')}}"></script>
<script src="{{asset('customers/js/jquery.sticky.js')}}"></script>

<!-- contact js -->
<script src="{{asset('customers/js/contact.js')}}"></script>
<script src="{{asset('customers/js/jquery.form.js')}}"></script>
<script src="{{asset('customers/js/jquery.validate.min.js')}}"></script>
<script src="{{asset('customers/js/mail-script.js')}}"></script>
<script src="{{asset('customers/js/jquery.ajaxchimp.min.js')}}"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{{asset('customers/js/plugins.js')}}"></script>
<script src="{{asset('customers/js/main.js')}}"></script>

</body>
</html>

resources/views/layouts/guest.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ "Undangan Nikah" }}</title>

    <!-- Scripts -->
    <link rel="stylesheet" href="/admins/css/app.css">
    <link rel="stylesheet" href="/admins/css/bootstrap-social.css">
    <link rel="icon" href="{{asset('/admins/img/logo.png')}}">
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Styles -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="/">
                    {{ "Undangan Nikah" }}
                </a>
                
                
                
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

</body>
</html>

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title')</title>
    <link rel="stylesheet" href="{{asset('admins/css/app.css')}}">
    <link rel="stylesheet" href="/admins/css/bootstrap-social.css">
    <link rel="icon" href="{{asset('/admins/img/logo.png')}}">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.22/css/dataTables.bootstrap4.min.css">
    <script src="https://kit.fontawesome.com/b34d9ac5d0.js" crossorigin="anonymous"></script>
</head>

<body class="hold-transition sidebar-mini">
    <style>
        #mapKu{
            position: relative;
            height: 500px;
            width: 100%;
        }
    </style>
    <div class="wrapper" id="app">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <!-- SEARCH FORM -->
            

        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="/" class="brand-link">
                <img src="{{asset('/admins/img/logo.png')}}" alt="Lara Logo" class="brand-image img-circle elevation-3"
                    style="opacity: .8">
                <span class="brand-text font-weight-light">Undangan Nikah</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="{{asset('/admins/img/profile.png')}}" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">
                            <h5>{{Auth::user()->name}}</h5> 
                
                        </a>
                    </div>
                </div>

                @if (Auth::user()->role == '1')
                    @include('layouts.sidebar_admin')
                @endif

            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    <div class="pt-5">
                        @include('common.alert')
                    </div>
                    @yield('content')
                    {{-- <router-view></router-view> --}}
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->

        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                Anything you want
            </div>
            <!-- Default to the left -->
            <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights
            reserved.
        </footer>
    </div>
    <!-- ./wrapper -->

    <!-- REQUIRED SCRIPTS -->
    {{-- <script type="application/javascript" src="{{asset('/js/app.js')}}"></script> --}}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>   
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.js"></script>     
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script> 
<script type="application/javascript" src="{{asset('/admins/js/adminlte.js')}}"></script>
</body>
    
    
    
@yield('js')


</html>

resources/views/layouts/sidebar_admin.blade.php
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
        data-accordion="false">
        <li class="nav-item" class="nav-link">
            <a href="/admin" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt blue"></i>
                <p>Beranda</p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{route('admin.pesanan.index')}}" class="nav-link">
                <i class="nav-icon fas fa-ticket-alt purple"></i>
                <p>
                    Pesanan
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{route('admin.agama.index')}}" class="nav-link">
                <i class="nav-icon fa fa-praying-hands orange"></i>
                <p>
                    Agama
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="{{route('admin.sambutan.index')}}" class="nav-link">
                <i class="nav-icon fab fa-speaker-deck cyan"></i>
                <p>
                    Kata Sambutan
                </p>
            </a>
        </li>
        <hr>
        <li class="nav-item">
            <a href="{{ route('admin.logout') }}"
               onclick="event.preventDefault();
                          document.getElementById('logout-form').submit();" class="nav-link">
                <i class="nav-icon fas fa-power-off red"></i>
                <p>
                    Keluar
                </p>
            </a>
            <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </li>

    </ul>
</nav>