routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::group(['prefix' => 'cust'], function () {
    Auth::routes(['verify' => true]);
});

Route::group(['as' => 'customer.'], function () {
    Route::get('/', 'CustomerController@index');
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('login', 'AuthAdminController@showLoginForm')->name('admin.login');
    Route::post('login', 'AuthAdminController@login')->name('admin.postlogin');
    Route::post('logout', 'AuthAdminController@logout')->name('admin.logout');
});

Route::group(['prefix' => 'admin', 'middleware' => 'admin', 'as' => 'admin.'], function () {
    Route::resource('/', 'AdminController');
    Route::resource('/agama', 'AgamaController');
    Route::resource('/sambutan', 'SambutanController');
    Route::resource('/pesanan', 'PesananController');
    Route::put('/pesanan/ubahStatus/{id}', 'PesananController@changeStatus')->name('pesanan.changeStatus');
});

// Route::group(['prefix'=>'/admin','middleware'=>'admin'],function(){
//     Route::resource('/','AdminController');
// });

Route::get('/home', 'HomeController@index')->name('home');

app/Sambutan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Sambutan extends Model
{
    use SoftDeletes;
    protected $table = "sambutans";
    protected $guarded = [];
    public $with = ['agama'];

    public function agama(){
        return $this->belongsTo(Agama::class, 'agama_id');
    }

    public function pesanan()
    {
        return $this->hasMany(Pesanan::class, 'sambutan_id', 'id');
    }
}

app/Http/Controllers/SambutanController.php
<?php

namespace App\Http\Controllers;

use App\Agama;
use App\Http\Requests\SambutanRequest;
use App\Sambutan;
use Illuminate\Http\Request;

class SambutanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Sambutan::get();
        return view("admin.sambutan.index", compact("data"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $agama = Agama::get();
        return view("admin.sambutan.create", compact("agama"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SambutanRequest $request)
    {
        Sambutan::insert($request->except('_token'));
        return redirect()->route('admin.sambutan.index')->with('success',$this->SUCCESS_ADD_MESSAGE);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Sambutan  $sambutan
     * @return \Illuminate\Http\Response
     */
    public function show(Sambutan $sambutan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Sambutan  $sambutan
     * @return \Illuminate\Http\Response
     */
    public function edit(Sambutan $sambutan)
    {
        $agama = Agama::get();
        return view("admin.sambutan.edit", compact("sambutan","agama"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Sambutan  $sambutan
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sambutan $sambutan)
    {
        Sambutan::find($sambutan->id)->update($request->all());
        return redirect()->route("admin.sambutan.index")->with("success",$this->SUCCESS_UPDATE_MESSAGE);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Sambutan  $sambutan
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sambutan $sambutan)
    {
        Sambutan::find($sambutan->id)->delete();
        return redirect()->route('admin.sambutan.index')->with("success", $this->SUCCESS_DELETE_MESSAGE);
    }
}

resources/views/admin/sambutan/create.blade.php
@extends('layouts.layout')

@section('title','Tambah Sambutan')
@section('content')
    <div class="row pt-2">
        <div class="col-md-12">
            <div class="card card-green">
                <div class="card-header">
                    <h3 class="card-title">Sambutan</h3>
                </div>
                <div class="card-body">
                    <form action="{{route('admin.sambutan.store')}}" method="POST" class="form-group">
                        @csrf
                        <div class="form-body">
                            <div class="form-label">
                                <label for="agama">Agama</label>
                            </div>
                            <select name="agama_id" id="agama" class="form-control">
                                <option value="">Pilih Agama</option>
                                @foreach($agama as $i)
                                    <option value="{{$i->id}}">{{$i->agama}}</option>
                                @endforeach
                            </select>
                            <br>

                            <div class="form-label">
                                <label for="agama">Kata Pembuka</label>
                            </div>
                            <input type="text" name="pembuka_title" class="form-control">
                            <br>

                            <div class="form-label">
                                <label for="agama">Kata Penutup</label>
                            </div>
                            <input type="text" name="penutup_title" class="form-control">
                            <br>

                            <div class="form-label">
                                <label for="agama">Kalimat Pembuka</label>
                            </div>
                            <textarea name="pembuka_message" class="form-control" rows="6"></textarea>
                            <br>

                            <div class="form-label">
                                <label for="agama">Kalimat Penutup</label>
                            </div>
                            <textarea name="penutup_message" class="form-control" rows="6"></textarea>

                            <br>
                            <div class="form-footer">
                                <button type="submit" class="btn btn-primary">Tambah</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/sambutan/edit.blade.php
@extends('layouts.layout')

@section('title','Edit Sambutan')
@section('content')
    <div class="row pt-2">
        <div class="col-md-12">
            <div class="card card-green">
                <div class="card-header">
                    <h3 class="card-title">Sambutan</h3>
                </div>
                <div class="card-body">
                    <form action="{{route('admin.sambutan.update',['sambutan'=>$sambutan->id])}}" method="POST"
                          class="form-group">
                        @csrf
                        @method("PUT")
                        <div class="form-body">
                            <div class="form-label">
                                <label for="agama">Agama</label>
                            </div>
                            <select required name="agama_id" id="agama" class="form-control">
                                @foreach($agama as $i)
                                    @if($sambutan->agama_id == $i->id)
                                        <option selected value="{{$i->id}}">{{$i->agama}}</option>
                                    @else
                                        <option value="{{$i->id}}">{{$i->agama}}</option>
                                    @endif
                                @endforeach
                            </select>
                            <br>

                            <div class="form-label">
                                <label for="agama">Kata Pembuka</label>
                            </div>
                            <input type="text" value="{{$sambutan->pembuka_title}}" name="pembuka_title"
                                   class="form-control">
                            <br>

                            <div class="form-label">
                                <label for="agama">Kata Penutup</label>
                            </div>
                            <input type="text" value="{{$sambutan->penutup_title}}" name="penutup_title"
                                   class="form-control">
                            <br>

                            <div class="form-label">
                                <label for="agama">Kalimat Pembuka</label>
                            </div>
                            <textarea name="pembuka_message" class="form-control" rows="6">{{$sambutan->pembuka_message}}</textarea>
                            <br>

                            <div class="form-label">
                                <label for="agama">Kalimat Penutup</label>
                            </div>
                            <textarea name="penutup_message" class="form-control" rows="6">{{$sambutan->penutup_message}}</textarea>

                            <br>
                            <div class="form-footer">
                                <button type="submit" class="btn btn-primary">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/sambutan/index.blade.php
@extends('layouts.layout')
@section('title','Sambutan')
@section('content')
    <div class="row pt-2">
        <div class="col-md-12">
            <div class="card card-green">
                <div class="card-header">
                    <h3 class="card-title">Sambutan</h3>
                </div>

                <div class="card-body ">
                    <a href="{{route('admin.sambutan.create')}}">
                        <button class="btn btn-primary mb-4"><i class="fa fa-plus"></i>
                            Tambah Data
                        </button>
                    </a>
                    <div class="table-responsive">
                        <table id="table" class="table table-striped table-bordered">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Agama</th>
                                <th>Judul pembuka</th>
                                <th>Judul penutup</th>
                                <th>Pembuka</th>
                                <th>Penutup</th>
                                <th>Tanggal Dibuat</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($data as $m)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $m->agama->agama }}</td>
                                    <td>{{$m->pembuka_title}}</td>
                                    <td>{{$m->penutup_title}}</td>
                                    <td>{{$m->pembuka_message}}</td>
                                    <td>{{$m->penutup_message}}</td>
                                    <td>@dateFormat($m->created_at)</td>
                                    <td>

                                        @csrf
                                        <a href="{{route('admin.sambutan.edit',['sambutan'=>$m->id])}}">
                                            <button type="submit" class="btn btn-warning">
                                                <i class="fa fa-fw fa-edit" style="color:white"></i>
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <form action="{{route('admin.sambutan.destroy',['sambutan'=>$m->id])}}"
                                              method="POST">
                                            @method("DELETE")
                                            @csrf
                                            <button type="submit" onclick="return confirm('Are you sure?')"
                                                    class="btn btn-danger">
                                                <i class="fa fa-fw fa-trash"></i>
                                            </button>
                                        </form>
                                    </td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('js')
    <script>
        $(document).ready(function () {
            $('#table').DataTable();
        });
    </script>
@endsection